# Site settings
title: FxMath Trade Fusion AI
email: fxmathsolution@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: blog/fxturn # Leave empty if deploying to the root of GitHub Pages
url: https://fxmathsolution.github.io/fxturn/blog # Use localhost for local development
twitter_username: fxmath
github_username: fxmathsolution

# Build settings
plugins:
  - jekyll-feed

# Just the Docs configuration
#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
just_the_docs:
  nav_external_links:
    - title: GitHub
      url: https://github.com/fxmathsolution/fxturn
  search_enabled: true
  search_tokenizer_separator: /[\s\-/]+/
  aux_links:
    - title: GitHub
      url: https://github.com/your-repo

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  docs:
    output: true
    permalink: /:path/
